import { sub } from 'date-fns';

// Demo leads data shaped to backend schema
// Includes extra fields used by the existing table (title, price, created, stock, category)
const ProductsData = [
  {
    id: 1,
    // table helpers
    title: 'John Doe',
    price: 2500,
    category: 'lead',
    stock: true,
    created: sub(new Date(), { days: 3 }).toISOString(),
    // lead schema fields
    state: 'CA',
    loan_amount: 2500,
    first_name: 'John',
    last_name: 'Doe',
    address: '123 Market St',
    city: 'San Francisco',
    email: 'john.doe@example.com',
    zip: '94103',
    dob: '01/15/1988',
    ssn_1: '123',
    ssn_2: '45',
    ssn_3: '6789',
    license_number: 'D1234567',
    license_state: 'CA',
    employer_name: 'Acme Corp',
    job_title: 'Engineer',
    phone: '+1 (555) 123-4567',
    employer_phone: '+1 (415) 555-0011',
    bank_name: 'Bank of Test',
    routing_number: '021000021',
    account_number: '123456789012',
    sitename: 'zippycash',
  },
  {
    id: 2,
    title: 'Jane Smith',
    price: 5000,
    category: 'lead',
    stock: true,
    created: sub(new Date(), { days: 1 }).toISOString(),
    state: 'NY',
    loan_amount: 5000,
    first_name: 'Jane',
    last_name: 'Smith',
    address: '55 Broadway',
    city: 'New York',
    email: 'jane.smith@example.com',
    zip: '10006',
    phone: '+1 (212) 555-0100',
    license_number: 'S7654321',
    license_state: 'NY',
    routing_number: '026009593',
    account_number: '987654321000',
    sitename: 'zippycash',
  },
  {
    id: 3,
    title: 'Michael Chan',
    price: 1500,
    category: 'lead',
    stock: false,
    created: sub(new Date(), { days: 7 }).toISOString(),
    state: 'TX',
    loan_amount: 1500,
    first_name: 'Michael',
    last_name: 'Chan',
    email: 'm.chan@example.com',
    zip: '73301',
    phone: '+1 (512) 555-0111',
  },
  {
    id: 4,
    title: 'Aisha Patel',
    price: 2000,
    category: 'lead',
    stock: true,
    created: sub(new Date(), { days: 5 }).toISOString(),
    state: 'FL',
    loan_amount: 2000,
    first_name: 'Aisha',
    last_name: 'Patel',
    email: 'a.patel@example.com',
    zip: '33101',
    phone: '+1 (305) 555-0123',
  },
  {
    id: 5,
    title: 'Carlos Mendoza',
    price: 10000,
    category: 'lead',
    stock: true,
    created: sub(new Date(), { days: 9 }).toISOString(),
    state: 'IL',
    loan_amount: 10000,
    first_name: 'Carlos',
    last_name: 'Mendoza',
    email: 'c.mendoza@example.com',
    zip: '60601',
    phone: '+1 (773) 555-0167',
  },
  {
    id: 6,
    title: 'Emily Johnson',
    price: 500,
    category: 'lead',
    stock: false,
    created: sub(new Date(), { days: 12 }).toISOString(),
    state: 'WA',
    loan_amount: 500,
    first_name: 'Emily',
    last_name: 'Johnson',
    email: 'emily.j@example.com',
    zip: '98101',
    phone: '+1 (206) 555-0133',
  },
  {
    id: 7,
    title: 'Liam Nguyen',
    price: 3200,
    category: 'lead',
    stock: true,
    created: sub(new Date(), { days: 4 }).toISOString(),
    state: 'NJ',
    loan_amount: 3200,
    first_name: 'Liam',
    last_name: 'Nguyen',
    email: 'liam.nguyen@example.com',
    zip: '07097',
    phone: '+1 (973) 555-0102',
  },
  {
    id: 8,
    title: 'Noah Williams',
    price: 4200,
    category: 'lead',
    stock: false,
    created: sub(new Date(), { days: 11 }).toISOString(),
    state: 'GA',
    loan_amount: 4200,
    first_name: 'Noah',
    last_name: 'Williams',
    email: 'noah.williams@example.com',
    zip: '30301',
    phone: '+1 (404) 555-0188',
  },
  {
    id: 9,
    title: 'Olivia Brown',
    price: 900,
    category: 'lead',
    stock: true,
    created: sub(new Date(), { days: 15 }).toISOString(),
    state: 'OR',
    loan_amount: 900,
    first_name: 'Olivia',
    last_name: 'Brown',
    email: 'olivia.brown@example.com',
    zip: '97201',
    phone: '+1 (503) 555-0144',
  },
  {
    id: 10,
    title: 'Ethan Davis',
    price: 2500,
    category: 'lead',
    stock: true,
    created: sub(new Date(), { days: 13 }).toISOString(),
    state: 'AZ',
    loan_amount: 2500,
    first_name: 'Ethan',
    last_name: 'Davis',
    email: 'ethan.davis@example.com',
    zip: '85001',
    phone: '+1 (602) 555-0202',
  },
  {
    id: 11,
    title: 'Mia Garcia',
    price: 1800,
    category: 'lead',
    stock: false,
    created: sub(new Date(), { days: 20 }).toISOString(),
    state: 'CO',
    loan_amount: 1800,
    first_name: 'Mia',
    last_name: 'Garcia',
    email: 'mia.garcia@example.com',
    zip: '80202',
    phone: '+1 (720) 555-0190',
  },
  {
    id: 12,
    title: 'Ava Wilson',
    price: 7600,
    category: 'lead',
    stock: true,
    created: sub(new Date(), { days: 25 }).toISOString(),
    state: 'VA',
    loan_amount: 7600,
    first_name: 'Ava',
    last_name: 'Wilson',
    email: 'ava.wilson@example.com',
    zip: '20101',
    phone: '+1 (571) 555-0177',
  },
];

export default ProductsData;
